### ISSUE TITLE
Role

### ISSUE THREAD

**Issue by MozhdehRastegar** [jstjoe/admin_console#4]
Hi Joe, any chance we can add Role for the Agent side?  Samsung was asking..

**Comment by jstjoe** [comment]
Do they need custom roles? Or just the agent/admin distinction?

Agent/admin is easy, custom roles is much more difficult unfortunately.

**Comment by MozhdehRastegar** [comment]
Oh, def custom roles... Shannon would want the same (Adobe).  Thanks!

**Comment by jstjoe** [comment]
Okay not THAT difficult :)

Sneak peek:
![screen shot 2015-04-06 at 2 16 29 pm](https://cloud.githubusercontent.com/assets/2015604/7012684/c6d96458-dc67-11e4-87bb-049f6004eb40.png)

**Comment by MozhdehRastegar** [comment]
WOOT!  Can I send this now to Samsung?  How does this work :)

On Mon, Apr 6, 2015 at 2:19 PM, Joseph McCarron notifications@github.com
wrote:

> Closed #4 https://github.com/jstjoe/admin_console/issues/4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jstjoe/admin_console/issues/4#event-274556526.

## 

"What is measured truly does improve." - Zendesk Benchmark Report
https://www.zendesk.com/blog/customer-satisfaction-trends-benchmark-2014

Customer Success Executive  | m: 408-206-1678 |  skype: +1 415 315 9608
Zendesk http://www.zendesk.com/

**Comment by jstjoe** [comment]
Not yet. I'll tell you more soon, but this will be one of our paid apps. They should be live in the marketplace by the end of the month. Do you think that wait will be a problem?

**Comment by MozhdehRastegar** [comment]
Oh crap, I might have told them they would get it for free.. Shoot!  Oh
well, I can backtrack I suppose :)  Do you know how much it would be for?
They are in big need of it now... but if they have to wait, they have to
wait..

On Mon, Apr 6, 2015 at 4:03 PM, Joseph McCarron notifications@github.com
wrote:

> Not yet. I'll tell you more soon, but this will be one of our paid apps.
> They should be live in the marketplace by the end of the month. Do you
> think that wait will be a problem?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jstjoe/admin_console/issues/4#issuecomment-90275236.

## 

"What is measured truly does improve." - Zendesk Benchmark Report
https://www.zendesk.com/blog/customer-satisfaction-trends-benchmark-2014

Customer Success Executive  | m: 408-206-1678 |  skype: +1 415 315 9608
Zendesk http://www.zendesk.com/
